msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-05-23 00:27+0300\n"
"PO-Revision-Date: 2017-05-23 00:30+0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.9\n"
"X-Poedit-Basepath: calibre-cloud-plugin\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SearchPath-0: main.py\n"

#: main.py:78
msgid "Logout successful"
msgstr "Oturum başarıyla kapatıldı"

#: main.py:98
msgid "Login information is incorrect!"
msgstr "Giriş bilgileri yanlış!"

#: main.py:104
msgid ""
"It was created because there is no Calibre file in Drive, download could not "
"be done."
msgstr ""
"Drive'da Calibre dosyanız olmadığından oluşturuldu, download yapılmadı."

#: main.py:107 main.py:321
msgid "Download complete."
msgstr "İndirme tamamlandı."

#: main.py:112 main.py:313
msgid "Upload complete."
msgstr "Yükleme tamamlandı."

#: main.py:116
msgid ""
"It was created because there is no Calibre file in Drive, pull could not be "
"done."
msgstr "Drive'da Calibre dosyanız olmadığından oluşturuldu, pull yapılmadı."

#: main.py:119
msgid "Pull complete."
msgstr "Pull tamamlandı."

#: main.py:124
msgid "Push complete."
msgstr "Push tamamlandı."

#: main.py:200
msgid "Auth successful."
msgstr "Kimlik doğrulama başarılı."

#: main.py:306
msgid "Deauth successful."
msgstr "Oturum başarıyla kapatıldı."

#: main.py:323
msgid "Calibre file does not exist on your Drive!"
msgstr "Drive'ınızda Calibre dosyası mevcut değil!"

#: main.py:334
msgid "Local or server files are synchronized with this plugin."
msgstr "Bu eklenti yereldeki veya sunucudaki dosyaları sekronize eder."

#: main.py:337
msgid "This program comes with absolutely no warranty.\n"
msgstr ""

#: main.py:338
msgid "See the GNU General Public License, version 3 or "
msgstr ""

#: main.py:339
msgid "later for details."
msgstr ""

#: main.py:359
msgid "Could not open url."
msgstr ""
